language: android
jdk: oraclejdk8
sudo: false

notifications:
    email:
        - orafaaraujo@gmail.com
env:
    matrix:
        # - ANDROID_TARGET=android-17 ANDROID_ABI=armeabi-v7a
        # - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
         - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
    global:
        - ADB_INSTALL_TIMEOUT=5    # Time out to 10 mins

android:
    update_sdk: true
    components:
        - tools
        - tools
        - platform-tools
        - build-tools-25.0.2
        - $ANDROID_TARGET

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        # System images
        - sys-img-armeabi-v7a-$ANDROID_TARGET

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
    - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"